# Generated by Django 5.1.2 on 2024-10-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location_letter',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Fach'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Schublade'),
        ),
    ]
