# Generated by Django 5.1.2 on 2024-10-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_inventoryitem_location_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='low_quantity',
            field=models.IntegerField(default=3, verbose_name='Mindestbestand'),
        ),
    ]
