# Generated by Django 5.1.2 on 2024-10-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_low_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='order_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Bestell-Link'),
        ),
    ]
