# Generated by Django 5.1.2 on 2024-11-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_order_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location_letter',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Schrank'),
        ),
    ]
