# Generated by Django 5.1.2 on 2024-11-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
