# Generated by Django 5.1.2 on 2024-11-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_barcode_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
    ]
