# Generated by Django 5.1.2 on 2024-11-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryitem_location_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location_shelf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fach'),
        ),
    ]
