# Generated by Django 5.1.2 on 2025-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_applicationtag_inventoryitem_application_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Wartungs-/Ablaufdatum'),
        ),
    ]
