# Generated by Django 5.1.2 on 2025-07-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventoryitem_image_inventoryitem_maintenance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_base_url', models.CharField(default='http://127.0.0.1:8000', help_text='Basis-URL für QR-Code-Links, z.\u202fB. http://192.168.178.20:8000', max_length=200)),
            ],
            options={
                'verbose_name': 'Globale Einstellung',
                'verbose_name_plural': 'Globale Einstellungen',
            },
        ),
    ]
