# Generated by Django 5.1.2 on 2025-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_globalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeOverviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'QR-Code Übersicht',
                'verbose_name_plural': 'QR-Code Übersicht',
                'managed': False,
            },
        ),
    ]
