# Generated by Django 5.1.2 on 2025-07-28 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_qrcodeoverviewmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(max_length=200, verbose_name='Entleiher')),
                ('quantity', models.PositiveIntegerField(verbose_name='Anzahl')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ausgeliehen am')),
                ('returned', models.BooleanField(default=False, verbose_name='Zurückgegeben?')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Zurückgegeben am')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='inventory.inventoryitem')),
            ],
        ),
    ]
