# Generated by Django 5.1.2 on 2025-07-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_borroweditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borroweditem',
            old_name='quantity',
            new_name='quantity_borrowed',
        ),
        migrations.AddField(
            model_name='borroweditem',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentar'),
        ),
    ]
