# Generated by Django 5.1.2 on 2025-07-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_quantity_borroweditem_quantity_borrowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borroweditem',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geplantes Rückgabedatum'),
        ),
    ]
