# Generated by Django 5.1.2 on 2025-07-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_borroweditem_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='soll_bestand',
            field=models.PositiveIntegerField(default=5, verbose_name='Soll-Bestand'),
        ),
    ]
