# Generated by Django 5.1.2 on 2025-07-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventoryitem_soll_bestand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='soll_bestand',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='low_quantity',
            field=models.IntegerField(default=3, verbose_name='Grundpuffer'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Ist-Bestand'),
        ),
    ]
