# Generated by Django 5.1.2 on 2025-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_inventoryitem_soll_bestand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('consumable', 'Verbrauchsmaterial')], default='equipment', max_length=20, verbose_name='Art des Artikels'),
        ),
    ]
