# Generated by Django 5.1.2 on 2025-07-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_inventoryitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorit'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Nutzung'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='qr_base_url',
            field=models.CharField(default='http://127.0.0.1:8000', help_text='Basis-URL für QR-Code-Links, z. B. http://192.168.178.20:8000', max_length=200),
        ),
    ]
