# Generated by Django 5.1.2 on 2025-07-31 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_inventoryitem_is_favorite_inventoryitem_last_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag-Typ')),
            ],
        ),
        migrations.AddField(
            model_name='applicationtag',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='inventory.tagtype', verbose_name='Typ'),
        ),
    ]
