# Generated by Django 5.1.2 on 2025-08-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_page_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
