# Generated by Django 5.1.2 on 2025-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_rolepermission_can_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='example_kwargs',
            field=models.JSONField(blank=True, default=dict, help_text="Beispiel-Parameter für reverse(), z.B. {'pk': 1}"),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(help_text="Menschlicher Name, z.B. 'Items Übersicht'", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='url_name',
            field=models.CharField(help_text="Der Name der URL in deinen admin_urls.py, z.B. 'admin_items'", max_length=100, unique=True),
        ),
    ]
