# Generated by Django 5.1.2 on 2025-08-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_page_example_kwargs_alter_page_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'permissions': [('manage_permissions', 'Kann Seiten-Berechtigungen verwalten')], 'verbose_name': 'Seite', 'verbose_name_plural': 'Seiten'},
        ),
    ]
