# Generated by Django 5.1.2 on 2025-08-03 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_storagelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.storagelocation', verbose_name='Lagerort'),
        ),
    ]
