# Generated by Django 5.1.2 on 2025-08-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_inventoryitem_storage_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagelocation',
            options={},
        ),
    ]
