# Generated by Django 5.1.2 on 2025-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0029_alter_storagelocation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, help_text='Emoji oder Icon (z. B. 🛠️)', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_quantity', models.BooleanField(default=True, verbose_name='Mengen anzeigen')),
                ('has_locations', models.BooleanField(default=True, verbose_name='Lagerorte verwenden')),
                ('has_min_stock', models.BooleanField(default=False, verbose_name='Mindestbestand verwenden')),
                ('enable_borrow', models.BooleanField(default=False, verbose_name='Verleih/Return verwenden')),
                ('is_consumable_mode', models.BooleanField(default=False, verbose_name='Verbrauchsmaterial-Logik')),
                ('require_qr', models.BooleanField(default=False, verbose_name='QR/Barcode Pflicht')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('categories', models.ManyToManyField(blank=True, help_text='Optional: Filter auf Kategorien.', to='inventory.category')),
                ('visible_for_groups', models.ManyToManyField(blank=True, help_text='Leer = für alle sichtbar.', to='auth.group')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
