# Generated by Django 5.1.2 on 2025-08-19 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0030_overview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borroweditem',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ausgeliehen am'),
        ),
        migrations.AlterField(
            model_name='borroweditem',
            name='return_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Geplantes Rückgabedatum'),
        ),
        migrations.AlterField(
            model_name='borroweditem',
            name='returned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Zurückgegeben?'),
        ),
        migrations.AlterField(
            model_name='borroweditem',
            name='returned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Zurückgegeben am'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('consumable', 'Verbrauchsmaterial')], db_index=True, default='equipment', max_length=20, verbose_name='Art des Artikels'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_used',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Letzte Nutzung'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location_letter',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True, verbose_name='Schrank'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location_number',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Schublade'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='low_quantity',
            field=models.IntegerField(db_index=True, default=3, verbose_name='Grundpuffer'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='maintenance_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Wartungs-/Ablaufdatum'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(db_index=True, verbose_name='Ist-Bestand'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='applicationtag',
            index=models.Index(fields=['type', 'name'], name='inventory_a_type_id_5274f6_idx'),
        ),
        migrations.AddIndex(
            model_name='borroweditem',
            index=models.Index(fields=['item', 'returned'], name='inventory_b_item_id_d6ee47_idx'),
        ),
        migrations.AddIndex(
            model_name='borroweditem',
            index=models.Index(fields=['returned', 'borrowed_at'], name='inventory_b_returne_2ba5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type', 'name'], name='inventory_c_type_id_dca69e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['item_type', 'is_active'], name='inventory_i_item_ty_1907f1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['item_type', 'category'], name='inventory_i_item_ty_aed10e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['location_letter', 'location_number'], name='inventory_i_locatio_1d9f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['date_created'], name='inventory_i_date_cr_0796c7_idx'),
        ),
        migrations.AddIndex(
            model_name='overview',
            index=models.Index(fields=['is_active', 'order'], name='inventory_o_is_acti_bbeedb_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['parent', 'name'], name='inventory_s_parent__3aebf5_idx'),
        ),
    ]
