# Generated by Django 5.1.2 on 2025-08-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_overviews',
            field=models.ManyToManyField(blank=True, help_text='Leer lassen = Zugriff auf alle aktiven Dashboards', related_name='allowed_users', to='inventory.overview'),
        ),
    ]
