# Generated by Django 5.1.2 on 2025-08-21 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_userprofile_allowed_overviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tags',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allowed_overviews',
            field=models.ManyToManyField(blank=True, help_text='Leer lassen = kein Zugriff auf Dashboards (explizit auswählen)', related_name='allowed_users', to='inventory.overview'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('done', 'Erledigt')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Erstellt am')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inventory.feedback', verbose_name='Feedback')),
            ],
            options={
                'verbose_name': 'Feedback-Kommentar',
                'verbose_name_plural': 'Feedback-Kommentare',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, '👍'), (-1, '👎')], verbose_name='Wert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='inventory.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback-Stimme',
                'verbose_name_plural': 'Feedback-Stimmen',
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status', 'created_at'], name='inventory_f_status_4704a9_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcomment',
            index=models.Index(fields=['feedback', 'created_at'], name='inventory_f_feedbac_a833ca_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackvote',
            index=models.Index(fields=['feedback', 'user'], name='inventory_f_feedbac_deafb3_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackvote',
            index=models.Index(fields=['feedback', 'value'], name='inventory_f_feedbac_43c476_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackvote',
            unique_together={('feedback', 'user')},
        ),
    ]
