# Generated by Django 5.2.7 on 2026-01-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_remove_userprofile_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('etage', models.CharField(max_length=10)),
                ('raum', models.CharField(max_length=20)),
                ('funktion', models.CharField(max_length=30)),
                ('nummer', models.CharField(max_length=10)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('sicherung', models.CharField(blank=True, max_length=20, null=True)),
                ('ziel', models.CharField(blank=True, max_length=100, null=True)),
                ('kabeltyp', models.CharField(blank=True, max_length=50, null=True)),
                ('laenge', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='aktiv', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('ha_link', models.URLField(blank=True, null=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='overview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.overview'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location_letter',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location_shelf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='maintenance_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.storagelocation'),
        ),
    ]
