# Generated by Django 5.2.7 on 2026-01-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_feedbacklastseen'),
        ('inventory', '0036_storagelocation_ha_entity_id'),
    ]

    operations = [
    ]
