# Generated by ChatGPT on 2025-09-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0036_storagelocation_ha_entity_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RolePermission",
        ),
        migrations.DeleteModel(
            name="Page",
        ),
    ]
