# Generated by Django 5.2.7 on 2026-01-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_merge_20260117_0855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackLastSeen',
        ),
    ]
