# Generated by ChatGPT on 2025-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0037_remove_page_rolepermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="overview",
            name="visible_for_groups",
        ),
        migrations.CreateModel(
            name="IntegrationStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Integration Status",
                "verbose_name_plural": "Integration Status",
            },
        ),
    ]
