# Generated by Django 5.2.10 on 2026-01-18 09:36

import uuid
from django.db import migrations, models
from django.db.models import Q


def populate_location_tokens(apps, schema_editor):
    StorageLocation = apps.get_model("inventory", "StorageLocation")
    existing = set(
        StorageLocation.objects.exclude(nfc_token__isnull=True)
        .exclude(nfc_token="")
        .values_list("nfc_token", flat=True)
    )
    for location in StorageLocation.objects.filter(Q(nfc_token__isnull=True) | Q(nfc_token="")):
        token = uuid.uuid4().hex[:16]
        while token in existing:
            token = uuid.uuid4().hex[:16]
        StorageLocation.objects.filter(pk=location.pk).update(nfc_token=token)
        existing.add(token)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0039_inventoryitem_nfc_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagelocation",
            name="nfc_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Token für NFC-Tags (wird automatisch erzeugt, wenn leer).",
                max_length=32,
                null=True,
                unique=True,
                verbose_name="NFC-Tag Token",
            ),
        ),
        migrations.RunPython(populate_location_tokens, migrations.RunPython.noop),
    ]
