# Generated by Django 5.2.10 on 2026-01-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0040_storagelocation_nfc_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="nfc_base_url_local",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Lokale Basis-URL für NFC-Links, z. B. http://192.168.178.20:8000",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="nfc_base_url_remote",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Remote/Tailscale Basis-URL für NFC-Links, z. B. https://host.tailnet-xyz.ts.net",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="nfc_base_choice",
            field=models.CharField(
                choices=[("local", "Lokal"), ("remote", "Tailscale/Remote")],
                default="local",
                help_text="Welche Basis-URL für NFC-Links verwendet werden soll.",
                max_length=12,
                verbose_name="NFC-Basis",
            ),
        ),
    ]
