# Generated by Django 5.2.10 on 2026-01-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0041_nfc_base_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagelocation",
            name="nfc_base_choice",
            field=models.CharField(
                choices=[("local", "Lokal"), ("remote", "Tailscale/Remote")],
                default="local",
                help_text="Welche Basis-URL für NFC-Links verwendet werden soll.",
                max_length=12,
                verbose_name="NFC-Basis",
            ),
        ),
    ]
