# Generated by Django 5.2.10 on 2026-01-18 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0043_overview_enable_quick_adjust"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Erstellt"),
                            ("updated", "Geändert"),
                            ("movement", "Lagerbewegung"),
                            ("quantity_adjusted", "Bestand angepasst"),
                            ("borrowed", "Ausgeliehen"),
                            ("returned", "Zurückgegeben"),
                            ("rollback", "Rollback"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("changes", models.JSONField(blank=True, default=list)),
                ("data_before", models.JSONField(blank=True, default=dict)),
                ("data_after", models.JSONField(blank=True, default=dict)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_history_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventar-Historie",
                "verbose_name_plural": "Inventar-Historie",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["item", "created_at"],
                        name="inventory_i_item_id_7de934_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="inventory_i_action_3bc5ff_idx",
                    ),
                ],
            },
        ),
    ]
