# Generated by Django 5.2.10 on 2026-01-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0045_scheduledexport_exportrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="show_admin_history",
            field=models.BooleanField(
                default=True, verbose_name="Admin-Historie & Rollback anzeigen"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="show_feedback",
            field=models.BooleanField(
                default=True, verbose_name="Feedback-Board anzeigen"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="show_movement_report",
            field=models.BooleanField(
                default=True, verbose_name="Lagerbewegungen anzeigen"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="show_patch_notes",
            field=models.BooleanField(
                default=True, verbose_name="Patch Notes anzeigen"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="show_scheduled_exports",
            field=models.BooleanField(
                default=True, verbose_name="Geplante Exporte anzeigen"
            ),
        ),
    ]
