# Generated by Django 5.2.10 on 2026-01-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0046_add_feature_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="show_mark_button",
            field=models.BooleanField(
                default=False, verbose_name="Markieren-Button anzeigen"
            ),
        ),
    ]
