# Generated by Django 5.2.10 on 2026-01-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0047_add_mark_button_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="overview",
            name="enable_mark_button",
            field=models.BooleanField(
                default=False, verbose_name="Markieren-Button anzeigen"
            ),
        ),
        migrations.AddField(
            model_name="overview",
            name="show_images",
            field=models.BooleanField(default=True, verbose_name="Bilder anzeigen"),
        ),
        migrations.AddField(
            model_name="overview",
            name="show_tags",
            field=models.BooleanField(default=True, verbose_name="Tags anzeigen"),
        ),
    ]
