# Generated by Django 5.2.10 on 2026-01-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0048_add_overview_display_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="overview",
            name="enable_advanced_filters",
            field=models.BooleanField(
                default=True, verbose_name="Erweiterte Suche/Filter"
            ),
        ),
        migrations.CreateModel(
            name="ItemAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=120)),
                ("file", models.FileField(upload_to="item_attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
