# Generated by Django 5.2.10 on 2026-01-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0049_add_overview_filters_and_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="enable_attachments",
            field=models.BooleanField(
                default=True, verbose_name="Dokumente/Bilder (Anhänge) erlauben"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="enable_bulk_actions",
            field=models.BooleanField(
                default=True, verbose_name="Bulk-Aktionen erlauben"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="enable_image_library",
            field=models.BooleanField(
                default=True, verbose_name="Bild-Bibliothek erlauben"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="enable_image_upload",
            field=models.BooleanField(
                default=True, verbose_name="Bild-Upload erlauben"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="enable_nfc_fields",
            field=models.BooleanField(default=True, verbose_name="NFC-Felder anzeigen"),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="enable_qr_actions",
            field=models.BooleanField(
                default=True, verbose_name="QR-Aktionen erlauben"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="show_favorites",
            field=models.BooleanField(
                default=True, verbose_name="Favoriten & Schnellzugriff anzeigen"
            ),
        ),
    ]
