# Generated by Django 5.2.10 on 2026-01-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0051_add_item_edit_feature_toggles"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("pcs", "Stück"),
                    ("set", "Set"),
                    ("pack", "Packung"),
                    ("box", "Box"),
                    ("m", "Meter"),
                    ("cm", "Zentimeter"),
                    ("mm", "Millimeter"),
                    ("kg", "Kilogramm"),
                    ("g", "Gramm"),
                    ("l", "Liter"),
                    ("ml", "Milliliter"),
                ],
                default="pcs",
                max_length=20,
                verbose_name="Einheit",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="variant",
            field=models.CharField(blank=True, max_length=120, verbose_name="Variante"),
        ),
        migrations.AddField(
            model_name="overview",
            name="enable_comments",
            field=models.BooleanField(
                default=False,
                help_text="Ermöglicht eine Kommentar-Aktion direkt aus dem Dashboard.",
                verbose_name="Kommentare/Feedback erlauben",
            ),
        ),
        migrations.AddField(
            model_name="overview",
            name="show_order_button",
            field=models.BooleanField(
                default=False,
                help_text="Zeigt die Nachbestellen-Aktion nur, wenn ein Bestell-Link vorhanden ist.",
                verbose_name="Nachbestellen-Button anzeigen",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_overviews",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional: persönliche Favoriten für Schnellzugriff.",
                related_name="favorited_by",
                to="inventory.overview",
            ),
        ),
    ]
