# Generated by Django 5.2.10 on 2026-01-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0052_inventoryitem_unit_inventoryitem_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="enable_unit_fields",
            field=models.BooleanField(default=True, verbose_name="Einheit anzeigen"),
        ),
    ]
