# Generated by Django 5.2.10 on 2026-01-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0053_globalsettings_enable_unit_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="tailscale_setup_complete",
            field=models.BooleanField(
                default=False, verbose_name="Tailscale-Setup abgeschlossen"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="tailscale_setup_confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tailscale-Setup bestätigt am"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="tailscale_setup_step",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 = nicht gestartet, 1 = installiert, 2 = verbunden, 3 = geteilt, 4 = bestätigt",
                verbose_name="Tailscale-Setup Schritt",
            ),
        ),
    ]
