# Generated by Django 5.2.10 on 2026-01-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0054_add_tailscale_setup_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="tailscale_setup_ignored",
            field=models.BooleanField(
                default=False, verbose_name="Tailscale-Setup ignoriert"
            ),
        ),
    ]
