# Generated by Django 5.2.10 on 2026-01-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0055_add_tailscale_setup_ignore"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="backup_interval_days",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 deaktiviert automatische Backups.",
                verbose_name="Backup-Intervall (Tage)",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="backup_retention_count",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Wie viele Backups im backup-Ordner behalten werden sollen.",
                verbose_name="Backup-Aufbewahrung (Anzahl)",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="last_backup_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Letztes Backup am"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="maintenance_message",
            field=models.TextField(
                blank=True, default="", verbose_name="Wartungsnachricht"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="maintenance_mode_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Wartungsmodus aktiv"
            ),
        ),
    ]
