# Generated by Django 5.2.10 on 2026-01-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0056_add_system_maintenance_and_backup_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="auto_maintenance_on_update",
            field=models.BooleanField(
                default=True,
                verbose_name="Wartungsmodus bei Updates automatisch aktivieren",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="backup_storage_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Leer = Standardpfad im Projekt.",
                max_length=255,
                verbose_name="Backup-Speicherort",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="role_plan_notes",
            field=models.TextField(
                blank=True, default="", verbose_name="Rollen-Plan (Notizen)"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="role_plan_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Rollen-Plan aktualisiert am"
            ),
        ),
    ]
