# Generated by Django 5.2.11 on 2026-02-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0062_merge_0061_add_overview_request_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("image", "Bild"),
                    ("operating_instruction", "Betriebsanweisung"),
                    ("manual", "Bedienungsanleitung"),
                    ("certificate", "Prüfprotokoll/Zertifikat"),
                    ("other", "Sonstiges"),
                ],
                default="other",
                max_length=40,
            ),
        ),
    ]
