# Generated by Django 5.2.11 on 2026-02-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0062_merge_0061_add_overview_request_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("documentation", "Dokumentation"),
                    ("manual", "Bedienungsanleitung"),
                    ("datasheet", "Datenblatt"),
                    ("certificate", "Prüfprotokoll / Zertifikat"),
                    ("invoice", "Rechnung / Beleg"),
                    ("image", "Foto"),
                    ("other", "Sonstiges"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
