# Generated by Django 5.2.15 on 2026-06-26 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_rename_inventory_i_item_id_e2a9b0_idx_inventory_i_item_id_253f36_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Markiert am')),
                ('cleared_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Aufgehoben am')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='inventory.inventoryitem', verbose_name='Markiertes Item')),
                ('location', models.ForeignKey(blank=True, help_text='Der unterste Knoten im StorageLocation-Baum, dem das Item zugeordnet ist.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to='inventory.storagelocation', verbose_name='Unterster Lagerort (LED-Ziel)')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Markiert von')),
            ],
            options={
                'verbose_name': 'Item-Markierung',
                'verbose_name_plural': 'Item-Markierungen',
                'ordering': ['-marked_at'],
                'indexes': [
                    models.Index(fields=['cleared_at', 'marked_at'], name='inventory_i_cleared_298e79_idx'),
                ],
            },
        ),
    ]
