# Generated by Django 5.2.15 on 2026-06-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_add_itemmark_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='active_git_branch',
            field=models.CharField(default='main', help_text='Branch, der aktuell ausgecheckt ist (wird beim Update-Wechsel aktualisiert).', max_length=100, verbose_name='Aktiver Git-Branch'),
        ),
    ]
